# Generated by Django 3.0.3 on 2021-03-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210312_2256'),
    ]

    query1 = "INSERT INTO socialaccount_socialapp(provider, name, client_id, secret) VALUES('google', 'Google API', '980985605567-923h1r4o8vhmv66prvh3h0lsv4phlkgv.apps.googleusercontent.com', 'XQRAoOhJ3jncptg2ZoJTYCX5')"
    query2 = "INSERT INTO socialaccount_socialapp_sites(socialapp_id, site_id) VALUES ((SELECT id FROM socialaccount_socialapp WHERE provider = 'google' LIMIT 1), 1)"

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='last name'),
        ),
        migrations.RunSQL(query1),
        migrations.RunSQL(query2)
    ]
