# Generated by Django 2.1 on 2019-03-11 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FairScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_down', models.IntegerField()),
                ('public_repo', models.IntegerField()),
                ('doi', models.IntegerField()),
                ('description', models.IntegerField()),
                ('api', models.IntegerField()),
                ('ontology', models.IntegerField()),
                ('documentation', models.IntegerField()),
                ('compatibility', models.IntegerField()),
                ('versions', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('citation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
                ('input_type', models.CharField(max_length=200)),
                ('output_type', models.CharField(max_length=200)),
                ('tags', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='fairscore',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Tool'),
        ),
    ]
