# Generated by Django 2.1 on 2019-03-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190314_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='FairScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findability', models.FloatField()),
                ('accessibility', models.FloatField()),
                ('interoperability', models.FloatField()),
                ('reusability', models.FloatField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Tool')),
            ],
        ),
    ]
