# Generated by Django 2.1 on 2019-03-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_fairscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessibility',
            name='totalPercentage',
        ),
        migrations.RemoveField(
            model_name='fairscore',
            name='reusability',
        ),
        migrations.RemoveField(
            model_name='findability',
            name='totalPercentage',
        ),
        migrations.RemoveField(
            model_name='interoperability',
            name='totalPercentage',
        ),
        migrations.RemoveField(
            model_name='reusability',
            name='totalPercentage',
        ),
    ]
