# Generated by Django 2.1 on 2019-03-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_pipeline_pipelinetools'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='accessibility',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='findability',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='interoperability',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='reusability',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
