# Generated by Django 2.1 on 2019-03-27 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0010_auto_20190324_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pipelinetools',
            name='branch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinetools',
            name='branchStart',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinetools',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinetools',
            name='toolAfter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_after', to='portal.Tool'),
        ),
        migrations.AddField(
            model_name='pipelinetools',
            name='toolBefore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_before', to='portal.Tool'),
        ),
        migrations.AddField(
            model_name='reusability',
            name='usesOnt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fairscore',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Tool'),
        ),
        migrations.AlterField(
            model_name='pipelinetools',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool', to='portal.Tool'),
        ),
    ]
