# Generated by Django 2.1 on 2019-03-27 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0011_auto_20190327_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatetool',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='output_type',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tags',
        ),
        migrations.AddField(
            model_name='tool',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PrivateTool',
        ),
    ]
