# Generated by Django 2.1 on 2019-03-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20190327_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='privateDesc',
            field=models.TextField(null=True),
        ),
    ]
