# Generated by Django 2.1 on 2019-05-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_remove_pipelinetools_branchstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibility',
            name='commandLine',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interoperability',
            name='sourceCode',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
