# Generated by Django 3.1.4 on 2020-12-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20190509_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('authors', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=400)),
            ],
        ),
    ]
