# Generated by Django 3.0.3 on 2020-12-08 18:23
from django.db import migrations, models
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.conf import settings
import requests
import json


def getlink(link):
    token = settings.BITLY_TOKEN

    headers = {
        'Authorization': f'Bearer {token}',
        'Content-Type': 'application/json',
    }

    data = json.dumps({"long_url": link.strip(), "domain": "bit.ly"})
    response = requests.post('https://api-ssl.bitly.com/v4/shorten', headers=headers, data=data)
    response_dict = json.loads(response.text)
    return response_dict["link"]


def is_url(link):
    link = link.strip()
    validate = URLValidator()
    try:
        validate(link)
        return True
    except ValidationError:
        return False


def shortenlinks(apps, schema_editor):
    reusability = apps.get_model("portal", "reusability")
    findability = apps.get_model("portal", "findability")

    for obj in reusability.objects.all():
        if is_url(obj.repositoryLink):
            obj.shortRepoLink = getlink(obj.repositoryLink)
        else:
            obj.shortRepoLink = ""

        obj.save()

    for obj in findability.objects.all():
        if is_url(obj.downlink):
            obj.shortDownLink = getlink(obj.downlink)
        else:
            obj.shortDownLink = ""

        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20190509_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='findability',
            name='shortDoiLink',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='findability',
            name='shortDownLink',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='reusability',
            name='shortRepoLink',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.RunPython(shortenlinks)
    ]

