# Generated by Django 3.0.3 on 2021-03-10 13:10

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20190509_1701'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE portal_findability SET doiLink = TRIM(REPLACE(REPLACE(doiLink, CHAR(13), ''), CHAR(10), ''));"),
        migrations.RunSQL(
            "UPDATE portal_findability SET downlink = TRIM(REPLACE(REPLACE(downlink, CHAR(13), ''), CHAR(10), ''));"),
        migrations.RunSQL(
            "UPDATE portal_reusability SET repositoryLink = TRIM(REPLACE(REPLACE(repositoryLink, CHAR(13), ''), CHAR(10), ''));")
    ]
