# Generated by Django 3.0.3 on 2020-12-08 18:23
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20201208_1931'),
    ]

    query = """
        UPDATE portal_findability
        SET doiLink = CONCAT('https://doi.org/', doiLink)
        WHERE doiLink IS NOT NULL and doiLink <> '' and doiLink not like 'http%' and doiLink <> 'No DOI found.' 
    """

    operations = [
        migrations.RunSQL(query)
    ]

